use axum::body::Body;
use axum::extract::State;
use axum::http::{Request, header};
use axum::response::IntoResponse;
use tracing::info;

use crate::rest::AppState;

pub(crate) async fn bootstrap_shytti(
    State(state): State<AppState>,
    req: Request<Body>,
) -> impl IntoResponse {
    let host = req.headers()
        .get("host")
        .and_then(|h| h.to_str().ok())
        .unwrap_or("localhost:7777");
    let scheme = if state.config_path.is_some() { "http" } else { "http" }; // TODO: detect TLS
    let hermytt_url = format!("{}://{}", scheme, host);
    let token = state.auth_token.clone().unwrap_or_default();

    let script = format!(r#"#!/bin/bash
set -e

# hermytt bootstrap: install shytti on this machine
# generated by {hermytt_url}

HERMYTT_URL="{hermytt_url}"
HERMYTT_KEY="{token}"
INSTALL_DIR="/opt/shytti"
SERVICE_NAME="shytti"

echo "=== hermytt bootstrap: shytti ==="
echo "hermytt: $HERMYTT_URL"

# Detect platform
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
case "$ARCH" in
    x86_64|amd64) ARCH="x86_64" ;;
    aarch64|arm64) ARCH="aarch64" ;;
    *) echo "unsupported arch: $ARCH"; exit 1 ;;
esac

echo "platform: $OS/$ARCH"

# Resolve latest shytti version
VERSION=$(curl -fsSL -o /dev/null -w '%{{url_effective}}' https://github.com/yttfam/shytti/releases/latest | grep -oE '[^/]+$')
echo "latest shytti: $VERSION"

# Download shytti binary
DOWNLOAD_URL="https://github.com/yttfam/shytti/releases/download/$VERSION/shytti-$OS-$ARCH"
echo "downloading shytti from $DOWNLOAD_URL..."
sudo mkdir -p "$INSTALL_DIR"
sudo curl -fSL "$DOWNLOAD_URL" -o "$INSTALL_DIR/shytti" || {{
    echo "download failed — you may need to build shytti manually"
    echo "  git clone https://github.com/yttfam/shytti"
    echo "  cd shytti && cargo build --release"
    echo "  sudo cp target/release/shytti $INSTALL_DIR/"
    exit 1
}}
sudo chmod +x "$INSTALL_DIR/shytti"

# Write config
echo "writing config..."
sudo tee "$INSTALL_DIR/shytti.toml" > /dev/null << CONF
[hermytt]
url = "$HERMYTT_URL"
token = "$HERMYTT_KEY"

[shell]
default = "$(command -v zsh || command -v bash || echo /bin/sh)"
CONF
sudo chmod 600 "$INSTALL_DIR/shytti.toml"

# Write env file for systemd (avoids token in unit file / /proc/*/environ)
sudo tee "$INSTALL_DIR/env" > /dev/null << ENV
HERMYTT_URL=$HERMYTT_URL
HERMYTT_KEY=$HERMYTT_KEY
ENV
sudo chmod 600 "$INSTALL_DIR/env"

# Chown config to the invoking user (not root) so the daemon can read it
RUN_USER="${{SUDO_USER:-$(whoami)}}"
sudo chown "$RUN_USER" "$INSTALL_DIR" "$INSTALL_DIR/shytti.toml" "$INSTALL_DIR/env"

# Install systemd service
if command -v systemctl &> /dev/null; then
    if systemctl is-active --quiet "$SERVICE_NAME" 2>/dev/null; then
        echo "stopping existing shytti service..."
        sudo systemctl stop "$SERVICE_NAME"
    fi
    echo "installing systemd service..."
    sudo tee /etc/systemd/system/$SERVICE_NAME.service > /dev/null << SVC
[Unit]
Description=shytti — shell orchestrator for hermytt
After=network.target

[Service]
Type=simple
User=$(whoami)
ExecStart=$INSTALL_DIR/shytti serve -c $INSTALL_DIR/shytti.toml
Restart=always
RestartSec=2
EnvironmentFile=$INSTALL_DIR/env

[Install]
WantedBy=multi-user.target
SVC

    sudo systemctl daemon-reload
    sudo systemctl enable "$SERVICE_NAME"
    sudo systemctl start "$SERVICE_NAME"
    sleep 2
    if systemctl is-active --quiet "$SERVICE_NAME"; then
        echo ""
        echo "=== shytti installed and running ==="
        echo "service: sudo systemctl status $SERVICE_NAME"
        echo "logs:    sudo journalctl -u $SERVICE_NAME -f"
        echo "config:  $INSTALL_DIR/shytti.toml"
    else
        echo "warning: service started but may have issues"
        echo "check:   sudo journalctl -u $SERVICE_NAME -e"
    fi
elif [ "$OS" = "darwin" ]; then
    PLIST_LABEL="com.yttfam.shytti"
    PLIST_PATH="/Library/LaunchDaemons/$PLIST_LABEL.plist"
    if sudo launchctl print system/$PLIST_LABEL &>/dev/null; then
        echo "stopping existing shytti daemon..."
        sudo launchctl bootout system/$PLIST_LABEL 2>/dev/null || true
        sleep 1
    fi
    echo "installing launchd daemon..."
    sudo tee "$PLIST_PATH" > /dev/null << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$INSTALL_DIR/shytti</string>
        <string>daemon</string>
        <string>-c</string>
        <string>$INSTALL_DIR/shytti.toml</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HERMYTT_URL</key>
        <string>$HERMYTT_URL</string>
        <key>HERMYTT_KEY</key>
        <string>$HERMYTT_KEY</string>
    </dict>
    <key>UserName</key>
    <string>$(whoami)</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$INSTALL_DIR/shytti.log</string>
    <key>StandardErrorPath</key>
    <string>$INSTALL_DIR/shytti.log</string>
</dict>
</plist>
PLIST
    sudo chmod 644 "$PLIST_PATH"
    sudo launchctl bootstrap system "$PLIST_PATH"
    sleep 2
    if sudo launchctl print system/$PLIST_LABEL &>/dev/null; then
        echo ""
        echo "=== shytti installed and running ==="
        echo "service: sudo launchctl print system/$PLIST_LABEL"
        echo "logs:    tail -f $INSTALL_DIR/shytti.log"
        echo "config:  $INSTALL_DIR/shytti.toml"
    else
        echo "warning: daemon loaded but may have issues"
        echo "check:   tail -50 $INSTALL_DIR/shytti.log"
    fi
else
    echo ""
    echo "=== shytti installed (no service manager) ==="
    echo "run manually: $INSTALL_DIR/shytti serve -c $INSTALL_DIR/shytti.toml"
fi
"#, hermytt_url = hermytt_url, token = token);

    info!("bootstrap script served");

    (
        [(header::CONTENT_TYPE, "text/x-shellscript")],
        script,
    )
}
